# Generated by Django 5.1.2 on 2024-10-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoDominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('resultado', models.JSONField()),
                ('dominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='servicios.dominio')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100)),
                ('resultado', models.JSONField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='servicios.ip')),
            ],
        ),
    ]
